name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Create .env file
      run: |
        echo "OPENAI_API_KEY=dummy_key" >> .env
        echo "ENV=dev" >> .env

    - name: Set up Docker Compose
      run: docker compose version

    - name: Build Containers
      run: docker compose -f docker-compose.yml build

    - name: Run Containers
      run: docker compose -f docker-compose.yml up -d

    - name: Wait for services
      run: sleep 15

    - name: Check running containers
      run: docker ps

    - name: Stop containers
      run: docker compose down
